name: CI
on:
  push:
    branches: [ master, alpha, beta ]
  pull_request:
    branches: [ master, alpha, beta ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test